### ISSUE TITLE
Implement real mailing list forms

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#112]
### Problem

The current site doesn't have functioning forms for signing up for our newsletter.

### Solution

Use the code that's on https://groupincome.org to implement a real functioning signup form.

**Comment by SebinSong** [comment]
@taoeffect is [this](https://github.com/okTurtles/groupincome.org-old) the github repo of the current https://groupincome.org/ website?

**Comment by taoeffect** [comment]
@SebinSong no, the current website has no repo (it's a wordpress site). If you need something send me a DM and I'll send it over to you.

But for this issue you can do "View Source" to grab the code for the form.
