### ISSUE TITLE
About Us: indicate there is more content below the fold

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/groupincome.org#121]
The `About Us` page needs a `v` after the first section (just like on homepage) to clearly indicate there's content below the fold. Please add :)

**Comment by SebinSong** [comment]
@taoeffect I just tried this in https://groupincome.org/about-us/ and found out the arrow button does not work.
Let me re-open this issue and fix it.

![image](https://github.com/user-attachments/assets/82101d0e-f4d2-4f15-aa50-09fcde0f00bf)

**Comment by taoeffect** [comment]
Good catch. I'm surprised - as I did test your PR...
