### ISSUE TITLE
Hovering over Group Income shorts at bottom of FAQ doesn't look like a link

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#125]
### Problem

When you hover over the shorts at the bottom of the FAQ page the cursor doesn't turn into a hand.

The videos don't look very clickable.

### Solution

Make it obvious these are links.

**Comment by SebinSong** [comment]
@taoeffect 
I think current [blog page](https://groupincome.org/blog/) seems to have a good example of images as a link. (Also referenced [this page](https://ux.stackexchange.com/questions/20697/how-to-indicate-that-an-image-is-a-link-too) too)

where the images have,

- drop-shadow. (helps imply the element can be depressed.)
- has title right below it.

<img src='https://github.com/user-attachments/assets/d92f8a72-727d-41df-8212-13abc8b2c33c' width='540'>

So, along with your request to make sure the cursor turns into a hand on hover state, I will make these updates too.

**Comment by taoeffect** [comment]
@SebinSong yeah good idea 👍
