### ISSUE TITLE
Blog Page - Mobile Review

### ISSUE THREAD

**Issue by leihla** [okTurtles/groupincome.org#13]
- [x] Update font-size of the title to 2.25rem and line-height:1.2;
<img width="376" alt="Screen Shot 2021-11-22 at 15 24 35" src="https://user-images.githubusercontent.com/158178/142888835-db5cedfd-5190-4d57-88d3-8a6c92866317.png">

___
- [x] Update .c-blog-title line-height to 1.4;
<img width="380" alt="Screen Shot 2021-11-22 at 15 27 17" src="https://user-images.githubusercontent.com/158178/142888830-313e268c-c4e7-45ce-8b61-ad8b24b84b75.png">

___
- [x] Videos inside blog post should be responsive
<img width="376" alt="Screen Shot 2021-11-22 at 15 28 18" src="https://user-images.githubusercontent.com/158178/142888823-9a9e5d74-52fa-44ff-9cc2-2a46162033be.png">

___
- [x] Read next section is not responsive ye
<img width="375" alt="Screen Shot 2021-11-22 at 15 28 46" src="https://user-images.githubusercontent.com/158178/142888813-98b8ac6b-b7ea-4dff-ade5-2d3667f44674.png">

___

- [x] Update font-size of the title to 3rem and line-height:1.2; (on tablet)
<img width="913" alt="Screen Shot 2021-11-22 at 15 34 40" src="https://user-images.githubusercontent.com/158178/142889704-88318eb3-1be6-4010-b7c4-6fad6de8da89.png">
<img width="915" alt="Screen Shot 2021-11-22 at 15 33 10" src="https://user-images.githubusercontent.com/158178/142889725-21437102-0f37-45fe-9c1a-25e32567f632.png">

**Comment by pieer** [comment]
Done
