### ISSUE TITLE
Update team member links

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/groupincome.org#130]
In the "Our Team" section of the `About Us` page, update the following team member links to be:

- Sebin Song: https://sebinsong.com/
- Ian Wesson: https://github.com/CrazedCoding

**Comment by Silver-IT** [comment]
Is it fine to add me to the list of contributors? 😁
Alex Jin: https://github.com/silver-it

**Comment by SebinSong** [comment]
Will definitely add yours too @Silver-IT

**Comment by taoeffect** [comment]
Not sure how we missed @Silver-IT! 😱

He definitely belongs there! 💪
