### ISSUE TITLE
FAQ Page - Mobile Review

### ISSUE THREAD

**Issue by leihla** [okTurtles/groupincome.org#14]
- [x] Page title has a extra margin right making the title not centered
<img width="378" alt="Screen Shot 2021-11-22 at 15 52 27" src="https://user-images.githubusercontent.com/158178/142892862-1e02b4b3-4b93-45ec-8696-71514e1cb569.png">

___

- [x] Navigation is missing the active section marked with bold, and updated as I scroll down the page
- [x] We could have all groups presented in a single line with a scroll, but we can also leave it as is
- [x] There's a 10px gap from the fixed navigation to the header, which makes text visible when scrolling

<img width="376" alt="Screen Shot 2021-11-22 at 15 43 54" src="https://user-images.githubusercontent.com/158178/142891601-c9a5510c-8380-4df1-9456-7eb79bc5ed87.png">

____

- [x] Clicking an link on the navigation makes section title and anchor point stay behind the menu. Title should still be visible

<img width="379" alt="Screen Shot 2021-11-22 at 15 44 20" src="https://user-images.githubusercontent.com/158178/142891611-230538ab-7d34-472c-ba2f-324163051102.png">

___

- [x] The padding on the questions is not consistent, and when it has two or three lines it starts to get on top of the lines. Passing should always be the same independent of the number of lines of text

<img width="378" alt="Screen Shot 2021-11-22 at 15 45 05" src="https://user-images.githubusercontent.com/158178/142891620-0272386a-26b1-470e-afd3-7dc2aca75b04.png">

- [x] The same happens when the questions are expanded
<img width="383" alt="Screen Shot 2021-11-22 at 15 44 47" src="https://user-images.githubusercontent.com/158178/142891617-e5b55edc-26bf-4d75-99fa-44308f88f04b.png">
<img width="379" alt="Screen Shot 2021-11-22 at 15 44 41" src="https://user-images.githubusercontent.com/158178/142891615-79e4ad6d-cb2b-4f04-8a73-d8637325b9b0.png">
<img width="376" alt="Screen Shot 2021-11-22 at 15 44 31" src="https://user-images.githubusercontent.com/158178/142891613-2a1ff2eb-4b4d-4ff1-8052-6e63db739c31.png">

**Comment by taoeffect** [comment]
@leihla can you double check that these are fixed and close the issue if they are when you get back?

**Comment by leihla** [comment]
I've reviewed the changes and everything looks to be working fine. Great work @pieer :)

I've found a new bug with the navigation:

- Scrolling down the page updates which menu item is selected
- Going back up, instead of showing the correct section selected, it shows the previous one. Exemple: I'm at Mincome section, scroll back up to Groups section, but General section appears selected
- If possible, the nav bar should horizontally scroll to the active section

https://www.awesomescreenshot.com/video/6522431?key=78fe5013d91db691a6b88647695a2b0a
