### ISSUE TITLE
Everything goes wonky on the homepage when resizing the window

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#17]
If you load the site on desktop and resize the window width-wise to be as narrow as possible, and then scroll a bit, you get some wonky behavior.

For example, the narrow width view looks like this:

<img width="435" alt="Screen Shot 2021-12-12 at 3 29 26 PM" src="https://user-images.githubusercontent.com/138706/145734039-420310e4-0a9f-4259-b5fb-a031fe3168af.png">

Then somehow (I no longer can figure out how to reproduce this), when I resized the window back to large, it did this:

<img width="551" alt="Screen Shot 2021-12-12 at 3 26 16 PM" src="https://user-images.githubusercontent.com/138706/145734054-3f4fea96-e189-41f5-bd43-b3eb30a01f9a.png">

In both cases I was using Firefox 95.

**Comment by pieer** [comment]
Fixed

**Comment by taoeffect** [comment]
@pieer Some of the issues were fixed, but I just tried again in Firefox and the homepage scrolling / animations are still broken when you resize the window from large to small.

Are the animations really necessary? We could avoid the issues entirely and not worry about tweaks breaking the site.
