### ISSUE TITLE
The "How it works" section is broken

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#18]
A few issues with this section:

- "Add members" isn't a thing during setup

<img width="1168" alt="Screen Shot 2021-12-12 at 3 34 44 PM" src="https://user-images.githubusercontent.com/138706/145734158-ad495fe7-c642-41fa-a34c-a8c7cb155608.png">

- Set mincome shows the wrong screen

<img width="1182" alt="Screen Shot 2021-12-12 at 3 35 22 PM" src="https://user-images.githubusercontent.com/138706/145734177-34e5d7ae-4c26-4e82-badd-ba7b351fd0cd.png">

- These aren't implemented

<img width="235" alt="Screen Shot 2021-12-12 at 3 35 44 PM" src="https://user-images.githubusercontent.com/138706/145734191-ce0fd299-4122-48ab-9cc9-a1a778fc4ef4.png">

**Comment by pieer** [comment]
Fixed
