### ISSUE TITLE
FAQ section needs to be answered

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#19]
There is currently nothing but lorem ipsum text.

/cc @dotmacro @CChavinha @leihla

**Comment by dotmacro** [comment]
The [current FAQ text](https://gitlab.okturtles.org/okturtles/groupincome-blog/-/tree/FAQs) is on Gitlab.

**Comment by CChavinha** [comment]
Yes, I updated Andrea's old version for the Crowdfund. 
We can have a look at it again for the website. But I believe Andrea reviewed it, and we agreed it was ready to use at the time.

**Comment by pieer** [comment]
Done
