### ISSUE TITLE
Image alignment in blog posts

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#21]
### Problem

I'm not sure whether we have wordpress-like classes like `.alignright` (and corresponding `aligncenter` and `alrightleft`) to align images in blog posts, but if not we need them and we need to use them where appropriate.

For example, here is how the blog post **Anikó Fejes and Sandrina Pereira join Group Income!** should look like:

![Screen Shot 2023-01-09 at 6 38 51 PM](https://user-images.githubusercontent.com/138706/211429686-74ba90e0-52e0-4b5b-b1c3-e250255319a8.jpg)

And here is how it renders in the new site:

![Screen Shot 2023-01-09 at 6 39 11 PM](https://user-images.githubusercontent.com/138706/211429726-0f237459-eb8e-41f6-8bd2-3839b3b8336a.jpg)

### Solution

Create classes (if necessary) and add them to `img` elements in blog posts (where necessary).

**Comment by pieer** [comment]
Done
