### ISSUE TITLE
Clicking hamburger doesn't do anything

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#22]
### Problem

![Screen Shot 2023-01-09 at 6 42 24 PM](https://user-images.githubusercontent.com/138706/211430161-06bd95f6-7ca9-4c31-a772-6b5574d25f4b.jpg)

In Firefox I made the browser window narrow, and then tried clicking on the hamburger icon in the upper right. It did nothing.

### Solution

Make sure the hamburger icon works on all devices and browsers.

**Comment by pieer** [comment]
Since the sponsor is added the header is borken

**Comment by pieer** [comment]
Fixed
