### ISSUE TITLE
Missing Favicon and open graph images

### ISSUE THREAD

**Issue by leihla** [okTurtles/groupincome.org#24]
**Problem**:
Currently the favicon isn't showing and when sharing the link on a social network, a preview image does not appear

**Comment by SebinSong** [comment]
If I'm not misunderstood, looks like this issue has already been resolved. So closing it.

<img src='https://github.com/okTurtles/groupincome.org/assets/17641213/a2bd3512-8238-4cd7-8511-ddb59b50ea7d' width='430'>
