### ISSUE TITLE
Hiring Page not working

### ISSUE THREAD

**Issue by leihla** [okTurtles/groupincome.org#27]
**Problem**
When clicking Hiring in the main menu, it gives 404. If no jobs are open we should remove the page from the main menu and remove the link for "See Open Positions" on the about page.

We should always show at least the volunteering section of the Hiring page 
https://www.figma.com/file/TsreEdGTmMweBlZr9eqgIu/Group-Income-Website?node-id=1174%3A393&t=YJYOpIUWMSWM5Rzz-1

**Comment by pieer** [comment]
Done
