### ISSUE TITLE
Upgrade Donate page to Sponsors Page

### ISSUE THREAD

**Issue by leihla** [okTurtles/groupincome.org#28]
**Problem**
The Donate page has changes do "Sponsor" and new sections where added that haven't been implemented: 

- [x] Missing "Direct Cryptocurrency Donation" title above the crypto currency links

- [x] Missing the "OR" divider between Crypto and Credit Donations

- [x] Missing Silver Sponsors Section
- [x] Missing Individual Sponsors Sections

**Solution**

Implement page as per updated designs here [Figma](https://www.figma.com/file/TsreEdGTmMweBlZr9eqgIu/Group-Income-Website?node-id=3257%3A2473&t=YJYOpIUWMSWM5Rzz-1)

**Comment by pieer** [comment]
Done
