### ISSUE TITLE
About Page Review

### ISSUE THREAD

**Issue by leihla** [okTurtles/groupincome.org#28]
Team Section
- [ ] There are multiple links on the team section that give 404 or link to wrong places

Community Links

- [ ] Missing underline on hover on the buttons or text

**Comment by pieer** [comment]
Correct. @taoeffect do you have other links for this list?
Aaron Brodeur
Megan Cress
Ian Wesson
Joeri Pross
Victor Morrow
Arjun Banker
David Kim
Nathan Windsor

**Comment by dotmacro** [comment]
Can you update the links for:
Scott Santens => https://twitter.com/ScottSantens
Arjun Banker => https://read.cv/arjun

**Comment by pieer** [comment]
Done
