### ISSUE TITLE
Homepage - Sections not loading correctly

### ISSUE THREAD

**Issue by leihla** [okTurtles/groupincome.org#30]
**Problem**
In the homepage, some sections of the content are missing when the bar graph starts appearing. There should be 3 different sections during the bar animation:
- Why it matters - Every Individual is valuable
- Mincome - The minimum amount each one should receive
- With Group Income - Share your income with your friends and family
Currently only the last one appears.

Video: https://drive.google.com/file/d/1M3uE08XahszDy1Ah6MiggfVg59I9jyH_/view?usp=drivesdk

Also, on the pledges animation, the profile picture is not appearing 
![Screenshot 2023-01-16 at 14 42 12](https://user-images.githubusercontent.com/158178/212704495-4565d5cc-b488-4433-8566-b73dfeaef34d.png)

**Solution**
Add missing sections and copy.

**Comment by pieer** [comment]
Done
