### ISSUE TITLE
Homepage - Missing Sections

### ISSUE THREAD

**Issue by leihla** [okTurtles/groupincome.org#31]
**Problem**
The last 2 sections added to the homepage where not implemented:

1. Security and Privacy
![Screenshot 2023-01-16 at 14 43 49](https://user-images.githubusercontent.com/158178/212705085-164c6a3b-fd94-44e7-af70-6bcb107e6b8f.png)

3. How to get started (which replaces the current How it Works Section)
![Screenshot 2023-01-16 at 14 43 54](https://user-images.githubusercontent.com/158178/212705130-4f4805e6-df0e-4ac7-86a1-b30b071e3e4d.png)

**Solution**
Implement new sections according to [Figma](https://www.figma.com/file/TsreEdGTmMweBlZr9eqgIu/Group-Income-Website?node-id=1017%3A2693&t=YJYOpIUWMSWM5Rzz-1)

**Comment by pieer** [comment]
Done
