### ISSUE TITLE
Implement Fundraiser Widget

### ISSUE THREAD

**Issue by leihla** [okTurtles/groupincome.org#34]
**Problem**
Fundraiser widget hasn't been implemented
![Screenshot 2023-01-16 at 14 51 26](https://user-images.githubusercontent.com/158178/212706606-cb555c1e-fd83-4f77-8b3d-88804f5f9e12.png)

**Solution**
Implement according [Figma Designs](https://www.figma.com/file/TsreEdGTmMweBlZr9eqgIu/Group-Income-Website?node-id=3318%3A4666&t=YJYOpIUWMSWM5Rzz-1)

**Comment by pieer** [comment]
Design Implemented. We need to update the actual data

**Comment by SebinSong** [comment]
@taoeffect looks like it's implemented with dummy data currently and can be closed too if this is the scope of the issue.
