### ISSUE TITLE
Fixing images at bottom of FAQ

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#49]
![Screen Shot 2023-03-20 at 8 25 29 AM](https://user-images.githubusercontent.com/138706/226387680-76c98a2f-4b7e-463a-bdd5-cdd937abefb6.jpg)

**Comment by neshvig10** [comment]
I would like to work on this

**Comment by neshvig10** [comment]
Seems like someone has fixed this issue , images appear correctly

**Comment by SebinSong** [comment]
I'm seeing the images displayed correctly. Marking it 'closed'

<img src='https://github.com/okTurtles/groupincome.org/assets/17641213/fe11a99a-24c9-484b-b77b-638fd5339c5a'>
