### ISSUE TITLE
Page load hang + 100% cpu usage in Safari

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#5]
### Problem

When running `npm run dev` and visiting `http://localhost:3000/groupincome.org/` in Safari, Safari hangs and uses 100% CPU instead of loading the website.

It seems to not be an issue with Brave (Chromium) and Firefox though.

### Solution

Find out what part of the project is causing this, and then see if it's possible to fix. I checked if [wordpress-to-astro](https://github.com/okTurtles/wordpress-to-astro) also has this problem and it doesn't, so it might be worth seeing what's different between the two. Once difference I noticed is that `astro.config.mjs` in this project uses `vue()` (which makes sense). Another difference is that this project uses an outdated version of Astro. Would be worth checking if one of those is the issue or something else.

**Comment by pieer** [comment]
Fixed
