### ISSUE TITLE
Blog post missing features: embedding tweets and YouTube videos, + rendering markdown tables

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#6]
### Problem

The blog doesn't support embedding Tweets and YouTube videos.

### Solution

Copy from [wordpress-to-astro](https://github.com/okTurtles/wordpress-to-astro) the `astro.config.mjs` config and relevant dependencies (`'remark-breaks'`, `'remark-gfm'`, `'@remark-embedder/core'`, and `'@remark-embedder/transformer-oembed'`).

**Comment by pieer** [comment]
Blog post missing feature added
