### ISSUE TITLE
resizing page bug

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#67]
### Problem

There's a problem with animation rendering after resizing the page:

https://github.com/okTurtles/groupincome.org/assets/138706/ce21e7f0-6a1b-42a2-92a2-6604484cfd72

### Solution

Find & fix bug

**Comment by SebinSong** [comment]
@taoeffect It seems like this issue has been resolved already. please close it once you confirm it's gone too.

**Comment by taoeffect** [comment]
@SebinSong nope, this problem still exists, but in a different way:

https://github.com/okTurtles/groupincome.org/assets/138706/ac107b28-83c2-44f8-96d1-85e12488038f

See if you can fix it. If you think it's too difficult, I'm also completely fine with removing the animations entirely.

**Comment by SebinSong** [comment]
@taoeffect I did run into the same symtoms of that bug too. Through my investigation, it seems to happen particularly when the viewport is reduced below the mobile size and then increased back up to the desktop size.
Will try and fix the issue after studying the [`gsap`](https://gsap.com/), (which is apparently the animation library that governs the animations there)

**Comment by SebinSong** [comment]
Figma link for the website:
https://www.figma.com/file/TsreEdGTmMweBlZr9eqgIu/Group-Income-Website
