### ISSUE TITLE
Typos & links on homepage

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/groupincome.org#69]
I found a few typos & missing/incorrect links on the homepage:

- "Get Started" button just above fold doesn't work (leads to 404)
- "Learn more about Basic Income" should be a link to FAQ
- "Why it matters?" should not have a "?" (change to "Why it matters")
- Under "Contribute", "independet" should be "independent"
- "Shelter Protocol" should now link to "https://shelterprotocol.net"
- In "How to get started" section 2 at bottom, "Read more about our technology" should be on its own line
- "Get Started" & "Sponsor" buttons near bottom of page don't work (lead to 404)

**Comment by neshvig10** [comment]
I would like to fix some of the issues

**Comment by SebinSong** [comment]
@neshvig10 Thanks for your interest but I'm already working on it.

**Comment by neshvig10** [comment]
Ok

**Comment by neshvig10** [comment]
Actually , All of these are very familiar to me :(

**Comment by neshvig10** [comment]
> @neshvig10 Thanks for your interest but I'm already working on it.

Have you done it ?
Cos I'm ready with the solutions
