### ISSUE TITLE
`npm run build` doesn't correctly generate site

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#7]
### Problem

The site is supposed to be generated with `npm run build`, but the generated site is built incorrectly, most likely due to an issue with how this project sets the value for `base` in the config.

Reproduce:

1. Run `npm run build`
2. Install `http-server` via Homebrew (on macOS), and run it inside of the `dist/` directory
3. Visit http://127.0.0.1:8080

You'll see many 404s generated in the output.

### Solution

Fix the `base` value, see [wordpress-to-astro](https://github.com/okTurtles/wordpress-to-astro) for an example.

**Comment by pieer** [comment]
Fixed
