### ISSUE TITLE
Misc Issues

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#82]
### Problem

This issue is here to keep track of miscellaneous random issues I find.

- [x] 2nd "Getting Started" button on homepage (above the down arrow button) [should be removed](https://www.figma.com/file/TsreEdGTmMweBlZr9eqgIu?node-id=3675:2917&mode=design#697824856)
- [x] Text in the scrolling animation section for "Every Individual Is Valuable" is not highlightable
- [x] After clicking a link (for example, "Read more about our privacy and security"), and then clicking the back button, we are not taken back to the scroll position we were at.
- [ ] 2 links at the bottom are broken: "Use [our official server](http://localhost:3000/groupincome.org/#)" and [Read more about our technology](http://localhost:3000/groupincome.org/#)
- [x] Most of the links on the homepage (and probably elsewhere) don't turn into a pointer finger when hovering over them.  Some of them do: "Hiring", "Sponsor" and "Get Started" in the menu turn into a pointer. Hovering over any link should turn the cursor into a pointer finger.

### Solution

You can submit a PR to close all of these issues or only some of them at a time.

**Comment by SebinSong** [comment]
Hi @taoeffect,

> 2 links at the bottom are broken: "Use [our official server](http://localhost:3000/groupincome.org/#)" and [Read more about our technology](http://localhost:3000/groupincome.org/#)

what is the correct url for the 'our official server' link here?

**Comment by taoeffect** [comment]
@SebinSong You can leave it blank for now as we haven't really set up the server yet (only the beta testing servers).

The second link can link to https://shelterprotocol.net
