### ISSUE TITLE
Update Homepage with latest changes

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#86]
### Problem

While the current homepage is looking good, it could use a few improvements.

### Solution

I've gone through and created a new homepage design here: https://www.figma.com/file/TsreEdGTmMweBlZr9eqgIu/Group-Income-Website?type=design&node-id=5234%3A2393&mode=design&t=lf4ADSAOvhKjT8zy-1

- The text in several sections have been updated
- Some of the graphs have been re-arranged
- The footer has some updates (Reddit => Forum)
- One section has been replaced with a new one about the chat features
- The year in the copyright footer has been updated (can you see if you can get it to be computed so we don't have to update it every year?)

Go through line-by-line and update the text in the various sections, as well as the various other updates like the graphs and the chat screenshot (which I've attached to this issue in case it helps).

![Screenshot 2024-02-20 at 11 07 02 AM](https://github.com/okTurtles/groupincome.org/assets/138706/dca65a22-369f-478c-b524-9ffe9923e1d8)

EDIT: note: need to get perms for this screenshot and also need to update it with Snowteamer and Ian.

**Comment by SebinSong** [comment]
@taoeffect 
As you can see from below, there is a same link placed in two consecutive sections. Do you think it has to be removed from one place or is it placed in both on purpose?

![image](https://github.com/okTurtles/groupincome.org/assets/17641213/fb6b8802-9b0f-46f2-a337-b9903525a5dc)

**Comment by taoeffect** [comment]
@SebinSong Both places is fine 👍
