### ISSUE TITLE
Design - make it clear that there's more info below on homepage

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#9]
While showing the website to a friend on his iPad, he didn't realize that you could scroll down the page. The iPad just perfectly captured the white portion of the top part of the homepage and it looked like that's all there was to the site.

A button of some sort in the center with an arrow pointing down could help with this. /cc @leihla

**Comment by leihla** [comment]
I had designed the icon but uploading it here as well for reference. cc @pieer 

<img width="697" alt="Screen Shot 2021-12-20 at 12 46 42" src="https://user-images.githubusercontent.com/158178/146769384-f3b830a2-8a3a-42ea-be64-600d37cb870e.png">

[Icon.svg.zip](https://github.com/okTurtles/groupincome.org/files/7745350/Icon.svg.zip)
